export const BANK_DATA = [
  {
    id: 1,
    bank: "SBI BANK",
  },
  {
    id: 2,
    bank: "AXIS BANK",
  },
  {
    id: 3,
    bank: "DENA BANK",
  },
  {
    id: 4,
    bank: "ICICI BANK",
  },
  {
    id: 5,
    bank: "Equitas Bank",
  },
  {
    id: 6,
    bank: "AU Bank",
  },
  {
    id: 7,
    bank: "IndusInd Bank",
  },
  {
    id: 8,
    bank: "Kotak Bank",
  },
  {
    id: 9,
    bank: "IDFC Bank",
  },
  {
    id: 10,
    bank: "Bank of Baroda",
  },
  {
    id: 11,
    bank: "CITI BANK",
  },
  {
    id: 12,
    bank: "Standard Chartered Bank",
  },
  {
    id: 13,
    bank: "HDFC Bank",
  },
  {
    id: 14,
    bank: "Navi Finserv (NBFC)",
  },
  {
    id: 15,
    bank: "Aditya Birla (NBFC)",
  },
  {
    id: 16,
    bank: "KNAB Finance (NBFC)",
  },
  {
    id: 17,
    bank: "L&T Finance (NBFC)",
  },
  {
    id: 18,
    bank: "Yes Bank",
  },
  {
    id: 19,
    bank: "Bajaj Finance (NBFC)",
  },
  {
    id: 20,
    bank: "Demat",
  },
  {
    id: 21,
    bank: "Mutual Fund",
  },
];

export const CREDIT_DATA = [
  {
    id: 1,
    title: "Bajaj EMI Card",
    bank: "Bajaj Finance (NBFC)",
    card: "Credit Card",
    annual_fee: "117",
    rank: 0,
    joining_fee: "599	",
  },
  {
    id: 2,
    title: "SBI Simply SAVE Credit Card",
    bank: "SBI BANK",
    card: "Simply SAVE",
    annual_fee: "499 + GST",
    rank: 7,
    joining_fee: "499 + GST	",
  },
  {
    id: 3,
    title: "Standard Chartered Bank Credit Card",
    bank: "Standard Chartered Bank",
    card: "Smart Credit Card",
    annual_fee: "499 + GST",
    rank: 9,
    joining_fee: "499 + GST	",
  },
  {
    id: 4,
    title: "HDFC Bank Credit Card",
    bank: "HDFC Bank",
    card: "Rewards",
    annual_fee: "250 + GST",
    rank: 10,
    joining_fee: "250 + GST	",
  },
  {
    id: 5,
    title: "ICICI Bank Platinum Credit Card",
    bank: "ICICI BANK",
    card: "Rewards",
    annual_fee: "Zero",
    rank: 8,
    joining_fee: "Zero",
  },
];
export const SAVING_DATA = [
  {
    id: 1,
    title: "AXIS ASAP",
    bank: "AXIS BANK",
    opening_charge: "Nil",
    min_balance: "10000",
    interest: "3.5% - 7.25% Per Annum	",
  },
  {
    id: 2,
    title: "Kotak 811",
    bank: "Kotak Bank",
    opening_charge: "Nil",
    min_balance: "Zero",
    interest: "4% Interest Rate*	",
  },
  {
    id: 3,
    title: "Yes Bank",
    bank: "Yes Bank",
    opening_charge: "Nil",
    min_balance: "5000",
    interest: "5% - 6.25% per annum",
  },
];
export const LOAN_DATA = [
  {
    id: 1,
    title: "L&T Finance",
    type: "Business Loan",
    bank: "L&T Finance (NBFC)",
    rank: "",
    interest: "11% - 26%",
    process_fee: "2% + applicable taxes",
    tenure_range: "12 - 48 months	",
  },
  {
    id: 2,
    title: "Abhi Loan",
    type: "Business Loan",
    bank: "KNAB Finance (NBFC)",
    rank: "",
    interest: "9% - 24%",
    process_fee: "2% or 1000 INR",
    tenure_range: "0 - 12 Months	",
  },
  {
    id: 3,
    title: "Aditya Birla",
    type: "Home Loan",
    bank: "Aditya Birla (NBFC)",
    rank: "",
    interest: "9%",
    process_fee: "NIL",
    tenure_range: "Upto 30 years	",
  },
  {
    id: 4,
    title: "Navi PL",
    type: "Personal Loan",
    bank: "Navi Finserv (NBFC)",
    rank: "",
    interest: "Starting from 9.9% P.A.",
    process_fee: "NIL",
    tenure_range: "6 Months - 5 years	",
  },
  {
    id: 5,
    title: "Aditya Birla Capital Business Loan",
    type: "Business Loan",
    bank: "SBI BANK",
    rank: "",
    interest: "Min. 14% Per Annum",
    process_fee: "Max. 2%",
    tenure_range: "1-4 years	",
  },
  {
    id: 6,
    title: "Citi Bank personal Loan",
    type: "Personal Loan",
    bank: "DENA BANK",
    rank: "",
    interest: "10.99% - 17.99% Per Annum",
    process_fee: "NIL",
    tenure_range: "30 Lakhs - Max.	",
  },
  {
    id: 7,
    title: "Axis Bank Home Loan",
    type: "Home Loan",
    bank: "AXIS BANK",
    rank: "85",
    interest: "3.5% - 7.25% Per Annum",
    process_fee: "Max. 1% ( upto Rs. 10000 + tax)",
    tenure_range: "3-30 years",
  },
];
export const LEAD_DATA = [
  {
    id: 1,
    date: "Feb 4, 2024	",
    name: "gyan test kotak	",
    mobile: "9999999999",
    bank: "SBI BANK",
    email: "gyantest@gmail.com",
    income: "777777777",
    pan: "",
    emp_status: "salaried",
    lead_type: "saving account",
    title: "	Kotak 811",
  },
  {
    id: 2,
    date: "Jan 11, 2024",
    name: "gyan	",
    mobile: "9898989898",
    bank: "SBI BANK",
    email: "gyan@gmail.com",
    income: "100000",
    pan: "",
    emp_status: "salaried",
    lead_type: "saving account",
    title: "	Kotak 811",
  },
  {
    id: 3,
    date: "Dec 22, 2023",
    name: "gyan test sbi	",
    mobile: "9742767000",
    bank: "SBI BANK",
    email: "gyantest@gmail.com",
    income: "1000000",
    pan: "",
    emp_status: "self-employed",
    lead_type: "credit card",
    title: "	SBI Simply SAVE Credit Card",
  },
  {
    id: 4,
    date: "Dec 22, 2023",
    name: "rahul	",
    mobile: "9898988989",
    bank: "SBI BANK",
    email: "rahulk3@gmail.com",
    income: "100000",
    pan: "",
    emp_status: "salaried",
    lead_type: "credit card",
    title: "	SBI Simply SAVE Credit Card",
  },
  {
    id: 5,
    date: "Dec 22, 2023",
    name: "sahaj	",
    mobile: "0099090909",
    bank: "SBI BANK",
    email: "s@gmailk.com",
    income: "1000000",
    pan: "",
    emp_status: "salaried",
    lead_type: "credit card",
    title: "	SBI Simply SAVE Credit Card",
  },
  {
    id: 6,
    date: "Dec 22, 2023",
    name: "gyan	",
    mobile: "9879865645",
    bank: "SBI BANK",
    email: "test@gmail.com",
    income: "11111111",
    pan: "",
    emp_status: "self-employed",
    lead_type: "credit card",
    title: "	SBI Simply SAVE Credit Card",
  },
  {
    id: 7,
    date: "Oct 6, 2023	",
    name: "dsd	",
    mobile: "1212121212",
    bank: "Standard Chartered Bank",
    email: "asdasd@ss.cc",
    income: "11111",
    pan: "",
    emp_status: "salaried",
    lead_type: "credit card",
    title: "	Standard Chartered Bank Credit Card",
  },
  {
    id: 8,
    date: "Jul 21, 2023",
    name: "demo	",
    mobile: "8770213581",
    bank: "AXIS BANK",
    email: "sunil2@gmail.com",
    income: "30000",
    pan: "",
    emp_status: "self-employed",
    lead_type: "saving account",
    title: "	AXIS ASAP",
  },
];
export const MUTUAL_FUND_DATA = [
  {
    id: 1,
    date: "Feb 4, 2024	",
    name: "gyan test kotak	",
    mobile: "9999999999",
    bank: "SBI BANK",
    email: "gyantest@gmail.com",
    income: "777777777",
    pan: "",
    emp_status: "salaried",
    lead_type: "saving account",
    title: "	Kotak 811",
  },
 
];
